name: Build and Deploy

on:
  push:
    branches:
      - main # Modifier si votre branche principale s'appelle autrement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Check token
      run: echo "Secret ${{ secrets.TOKEN }}"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./dist # Modifier si votre dossier de sortie est différent
